service: serverless-facebook-messenger-bot

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: GET
          path: webhook
          integration: lambda
      - http:
          method: POST
          path: webhook
          integration: lambda
